### PR TITLE
Support ActiveJob/Rails 8.0 rc1

### LINKED ISSUE #85: Rails 8 support
Can rails 8 support be added to the gem? I've started a test project with rails 8 and noticed this gem doesn't support it yet

### PR DESCRIPTION
**Pull request by sharshenov**
This PR allows to use `activejob-uniqueness` with Rails 8.0 rc1 and never versions

Resolves https://github.com/veeqo/activejob-uniqueness/issues/85

### CODE REVIEW

**Review by adis-io — APPROVED** [review]

**Comment by ineedjet** [comment]
it's about time

**Comment by jfilip** [comment]
Any change this can be merged / released? It's the one dependency holding back a Rails 8 upgrade for me.

**Comment by sharshenov** [comment]
The change is merged you can use it from them `main` branch.
The next release will ship it and https://github.com/veeqo/activejob-uniqueness/pull/82 once it is merged (eta this week)

**Comment by sharshenov** [comment]
https://rubygems.org/gems/activejob-uniqueness/versions/0.4.0

**Pull request merged**
