### PR TITLE
Update to Rails 7.1

### PR DESCRIPTION
**Pull request by caseyprovost**

### CODE REVIEW

**Comment by jscharf** [comment]
Thanks for opening this! We need this change as well so let me know if there's anything I can do to help work on it 🙌

**Comment by caseyprovost** [comment]
> Thanks for opening this! We need this change as well so let me know if there's anything I can do to help work on it 🙌

Any polishing and cleanup on this PR would be quite welcome. The lower the friction to merge the faster we all win 🎊

**Comment by pnicholls** [comment]
@caseyprovost is this required? https://github.com/veeqo/activejob-uniqueness/compare/main...wrapbook:activejob-uniqueness:chores/rails-71-upgrade#diff-596b513edba5e668d4270948322cf9737d32534c794d3e9e577ce78da6d5625cR32

Thanks for kicking this work off btw.

**Comment by caseyprovost** [comment]
> @caseyprovost is this required? [main...wrapbook:activejob-uniqueness:chores/rails-71-upgrade#diff-596b513edba5e668d4270948322cf9737d32534c794d3e9e577ce78da6d5625cR32](https://github.com/veeqo/activejob-uniqueness/compare/main...wrapbook:activejob-uniqueness:chores/rails-71-upgrade#diff-596b513edba5e668d4270948322cf9737d32534c794d3e9e577ce78da6d5625cR32)
> 
> ```
>   spec.add_dependency 'redis', '~> 4.8.1'
> ```
> 
> Thanks for kicking this work off btw.

I was getting file not found "redis" when trying to run the tests otherwise. It's possible I wasn't doing it properly though :thinkingface:

> @caseyprovost is this required? [main...wrapbook:activejob-uniqueness:chores/rails-71-upgrade#diff-596b513edba5e668d4270948322cf9737d32534c794d3e9e577ce78da6d5625cR32](https://github.com/veeqo/activejob-uniqueness/compare/main...wrapbook:activejob-uniqueness:chores/rails-71-upgrade#diff-596b513edba5e668d4270948322cf9737d32534c794d3e9e577ce78da6d5625cR32)
> 
> ```
>   spec.add_dependency 'redis', '~> 4.8.1'
> ```
> 
> Thanks for kicking this work off btw.


I was getting file not found "redis" when trying to run the tests otherwise. It's possible I wasn't doing it properly though 🤔

**Comment by bforma** [comment]
> Is anyone familiar with that file can comment on whether it's needed as part of the support for Rails 7.1?

Yes, you will have to add 7.1 support in the `Appraisals` file, like I did in my #63 PR.

**Comment by laurafeier** [comment]
Since the upgrade of redlock, we don't need redis anymore. I updated the specs to use redis-client, which is the current redlock dependency. See #65 #66

**Comment by sharshenov** [comment]
@caseyprovost thank you for the effort

I'm closing this Draft in favor of https://github.com/veeqo/activejob-uniqueness/pull/66

**Pull request closed without merging**
